=== maddysan0407/BankingApp/THE_Bank/cheque.dtd
<!ELEMENT THEbank (cheque*)>
<!ELEMENT payment_info (fname,lname,phone_number,email_address,ad_1,street,city,state,p_code)+>
<!ATTLIST payment_info Account_no CDATA #REQUIRED>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT phone_number (#PCDATA)>
<!ELEMENT email_address (#PCDATA)>
<!ELEMENT ad_1 (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT p_code(#PCDATA)>

=== maddysan0407/BankingApp/Server/THE_Bank/cheque.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE THEbank SYSTEM "./cheque.dtd">
<THEbank>
    <cheque Account_no="129e128ng">
        <fname>Soorya</fname>
        <lname>S</lname>
        <phone_number>9813276412</phone_number>
        <email_address>soorya.s@gmail.com</email_address>
        <ad_1>75-b,ground floor</ad_1>
	<street>louis lane</street>
	<city>Kochi</city>
	<state>Kerala</state>
	<p_code>123456</p_code>
	

    </cheque>
</THEbank>
